version: '3.8'

services:
  app:
    build: .
    container_name: marketplace_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs # Монтируем локальную папку configs в контейнер
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: marketplace_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: