version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: marketplace_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: marketplace_db
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: marketplace_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs # Монтируем локальную папку configs в контейнер
    depends_on:
      - db

volumes:
  db_data: