server:
  port: 8881

database:
  host: localhost
  port: 5432
  user: marketplace_first
  password: marketplace_first
  dbname: marketplace_supplier
  sslmode: disable

jwt:
  secret: supersecretkey1234567890
  expiration: 24h

whatsapp:
  api_url: https://api.whatsapp.com/send
  api_key: your_whatsapp_api_key