server:
  port: 8080

database:
  host: "db"     # Использует переменную из .env
  port: 5432        # Использует переменную из .env
  user: postgres       # Использует переменную из .env
  password: yourpassword
  dbname: marketplace_db    # Использует переменную из .env
  sslmode: disable

jwt:
  secret: supersecretkey1234567890
  expiration: 24h

whatsapp:
  api_url: https://api.whatsapp.com/send
  api_key: your_whatsapp_api_key